"""create chatgroup and groupmenbership table

Revision ID: b4c6d48b0a36
Revises: 2c43ee64c345
Create Date: 2023-12-06 16:03:45.278042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c6d48b0a36'
down_revision: Union[str, None] = '2c43ee64c345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
