"""create chatgroup and groupmenbership table new

Revision ID: c77c6cab7f46
Revises: b4c6d48b0a36
Create Date: 2023-12-06 16:11:32.291699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77c6cab7f46'
down_revision: Union[str, None] = 'b4c6d48b0a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_group_created_at'), 'chat_group', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_group_id'), 'chat_group', ['id'], unique=False)
    op.create_index(op.f('ix_chat_group_name'), 'chat_group', ['name'], unique=True)
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_membership_id'), 'group_membership', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_membership_id'), table_name='group_membership')
    op.drop_table('group_membership')
    op.drop_index(op.f('ix_chat_group_name'), table_name='chat_group')
    op.drop_index(op.f('ix_chat_group_id'), table_name='chat_group')
    op.drop_index(op.f('ix_chat_group_created_at'), table_name='chat_group')
    op.drop_table('chat_group')
    # ### end Alembic commands ###
